# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20161128_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='titlehash',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
