# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_titlehash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateTimeField(null=True, verbose_name='Movie year'),
        ),
    ]
