# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20161205_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
