# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20161206_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='profile',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.IntegerField(choices=[(0, 'Director'), (1, 'Actor'), (2, 'Producer'), (3, 'Screenplay'), (4, 'Director of Photography')], default=0),
        ),
    ]
