# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20161206_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='tmdb_id',
            field=models.IntegerField(null=True),
        ),
    ]
