# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_role_tmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='profile',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='tmdb_id',
            field=models.CharField(blank=True, default=0, max_length=200),
            preserve_default=False,
        ),
    ]
