# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20161206_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='movie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='people',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='movies.People'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.IntegerField(choices=[(0, 'Director'), (1, 'Actor'), (2, 'Producer'), (3, 'Screenplay'), (4, 'Director of Photography'), (5, 'Writer')], default=0),
        ),
        migrations.AlterField(
            model_name='role',
            name='tmdb_id',
            field=models.CharField(max_length=200),
        ),
    ]
