# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20161206_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
