# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-15 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_movie_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='possible',
            field=models.TextField(null=True),
        ),
    ]
