# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_movie_possible'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_id_not',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='possible',
            field=models.TextField(default=0, null=True),
        ),
    ]
