# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_auto_20161216_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='tmdb_id_not',
            new_name='search',
        ),
    ]
